# Copyright (c) 2020, The ZMK Contributors
# SPDX-License-Identifier: MIT

description: |
  Higher-order animation which allows for composing other animation
  drivers and using different blending modes.

compatible: "zmk,animation-compose"

properties:
  animations:
    type: phandles
    required: true
    description: |
      Animations to be combined.
